version: 2.1

jobs:
  lint-and-test-job:
    docker:
      - image: circleci/node:14.15.0
    steps:
      - checkout
      - restore_cache: # ref: https://circleci.com/docs/2.0/caching/#restoring-cache
          keys: 
            # Find a cache corresponding to this specific package-lock.json checksum
            # when this file is changed, this key will fail
            - v3-npm-deps-{{ checksum "package-lock.json" }}
            # Find the most recently generated cache used from any branch
            - v3-npm-deps-

      - restore_cache:
          key: node-v3-{{ checksum "package.json" }}

      - run: npm install

      - save_cache:
          key: v3-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      - save_cache:
          key: node-v3-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run: npm run lint

      - run:
          name: Jest Tests
          command: npm run test

workflows:
  # build-and-deploy-release: TODO to automate creation of npm modules
  #   jobs:
  #     - lint-and-test-job:
  #         filters:
  #           tags:
  #             only: /^v.*/
  #           branches:
  #             ignore: /.*/
              
  lint-and-test:
    jobs:
      - lint-and-test-job